stages:
  - build
  - test

build:
  stage: build
  tags:
    - cocktail
  script:
    - echo "Building the project..."
    # Add your build commands here

test:
  stage: test
  tags:
    - cocktail
  script:
    - echo "Testing the project..."
    # Add your test commands here
